# Generated by Django 4.1.5 on 2023-01-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_text', models.CharField(max_length=5000)),
                ('tweet_text_clean', models.CharField(default='na', max_length=5000)),
                ('tweet_sentiment', models.CharField(max_length=1)),
                ('request_number', models.IntegerField()),
            ],
        ),
    ]
