# Generated by Django 4.1.5 on 2023-02-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetSentiment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='negativetweets',
            old_name='subject',
            new_name='first_subject',
        ),
        migrations.AddField(
            model_name='negativetweets',
            name='second_subject',
            field=models.CharField(default='na', max_length=5000),
            preserve_default=False,
        ),
    ]
