# Generated by Django 4.1.5 on 2023-01-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetSentiment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesteddata',
            name='request_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
