# Generated by Django 4.1.5 on 2023-01-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetSentiment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NegativeTweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_text', models.CharField(max_length=5000)),
                ('personal_tweet', models.CharField(max_length=1)),
            ],
        ),
    ]
