# Generated by Django 4.1.5 on 2023-01-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetSentiment', '0002_requesteddata_request_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesteddata',
            name='tweet_text_clean',
            field=models.CharField(default='na', max_length=5000),
        ),
        migrations.AlterField(
            model_name='requesteddata',
            name='tweet_text',
            field=models.CharField(max_length=5000),
        ),
    ]
