# Generated by Django 4.1.5 on 2023-01-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetSentiment', '0002_negativetweets'),
    ]

    operations = [
        migrations.AddField(
            model_name='negativetweets',
            name='subject',
            field=models.CharField(default='n/a', max_length=5000),
            preserve_default=False,
        ),
    ]
