ACRONYM_TRANSLATE = {
'lol' : 'laughing out loud',
'omg': 'oh my god',
'imo' : 'in my opinion',
'imho': 'in my honest opinion',
'btw' : 'by the way',
'idk' : 'I do not know',
'lmk' : 'let me know',
'tbh' : 'to be honest',
'tgif' : 'thank goodness it is Friday',
'rofl' : 'rolling on floor laughing',
'brb' : 'be right back',
'bbl' : 'be back later',
'ttyl' : 'talk to you later',
'thx' : 'thanks',
'ty' : 'thank you',
'yw' : 'you are welcome',
'asap' : 'as soon as possible',
'pov' : 'point of view',
'nbd' : 'no big deal',
'omw' : 'on my way',
'diy' : 'do it yourself',
'aka' : 'also known as',
'sms' : 'short message service',
'oatus' : 'on a totally unrelated subject',
'icymi' : 'in case you missed it',
'stfu' : 'shut the fuck up',
'bf' : 'boyfriend',
'gf' : 'girlfriend',
'so' : 'significant other',
'ily' : 'I love you',
'yolo' : 'you only live once',
'irl' : 'in real life',
'tmi' : 'too much information',
'atm' : 'at the moment',
'bff' : 'best friends forever',
'byob' : 'bring your own beer',
'cu' : 'see you',
'ur' : 'you are',
'fyi' : 'for your information',
'fomo' : 'fear of missing out',
'smh' : 'shaking my head',
'jmo' : 'just my opinion',
'nvm' : 'never mind',
'gl' : 'good luck',
'fwiw' : 'for what it is worth',
'gbu' : 'god bless you',
'imnsho' : 'in my not so humble opinion',
'rn' : 'right now',
'tldr' : 'too long did not read',
'qotd' : 'quote of the day',
'tbf' : 'to be fair',
'dkdc' : 'do not know do not care',
'idc' : 'I do not care',
'k' : 'okay',
'cwot' : 'complete waste of time',
'lmao' : 'laughing my ass off',
'mu' : 'miss you',
'ssdd' : 'same stuff different day',
'xoxo' : 'hugs and kisses',
'ott' : 'over the top',
'plz' : 'please',
'dm' : 'direct message',
'ruok' : 'are you okay',
'spk' : 'speak',
'sry' : 'sorry',
'sup' : 'what is up',
'ttfn' : 'ta ta for now',
'vn' : 'very nice',
'wtf' : 'what the fuck',
'y' : 'why',
'jk' : 'just kidding',
'bc' : 'because',
'tbc' : 'to be confirmed',
'tba' : 'to be announced',
'tbd' : 'to be determined',
'faq' : 'frequently asked questions',
'na' : 'not applicable',
'tia' : 'thanks in advance',
'np' : 'no problem',
'eod' : 'end of day',
'eta' : 'estimated time of arrival',
'embm' : 'early morning business meeting',
'cta' : 'call to action',
'roi' : 'return on investment',
'vfm' : 'value for money',
'ctr' : 'click through rate',
'bogof' : 'buy one get one free',
'otp' : 'one time password',
'hth' : 'hope this helps',
'wfh' : 'work from home',
'u' : 'you',
'w' : 'with'
}